{{ if .Values.authHelper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.authHelper.resourcesName }}
  name: {{ .Values.authHelper.resourcesName }}
  namespace: {{ .Values.namespace  }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.authHelper.resourcesName }}
  template:
    metadata:
      labels:
        app: {{ .Values.authHelper.resourcesName }}
      namespace: {{ .Values.namespace }}
    spec:
      containers:
      - image: {{ .Values.authHelper.image.path }}
        imagePullPolicy: {{ .Values.authHelper.image.imagePullPolicy }}
        name: {{ .Values.authHelper.resourcesName }}
        env:
          - name: "UP9_DISABLE_LOGS_STDOUT"
            value: {{ .Values.logging.disableStdoutLogging | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authHelper.resourcesName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.authHelper.resourcesName }}
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Values.authHelper.resourcesName }}
{{ end }}