apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoleName }}
rules:
  - apiGroups: [ "", "extensions", "apps", "metrics.k8s.io"]
    resources: [ "pods", "services", "endpoints", "namespaces",  "ingresses", "configmaps", "deployments", "pods/log" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [ "extensions", "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch" ]
  - apiGroups: [ "", "extensions" ]
    resources: [ "pods" ]
    verbs: [ "deletecollection" ]
  - apiGroups: [ "", "extensions" ]
    resources: [ "configmaps" ]
    verbs: [ "patch", "get", "update" ]
